In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
nestedlist = [[1,2],[3,4],[5,6]]

In [5]:
nestedlist

[[1, 2], [3, 4], [5, 6]]

In [6]:
np.array(nestedlist)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((4,8), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [14]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(2)

array([0.21661727, 0.71018927])

In [19]:
np.random.rand(3,4)

array([[0.31445545, 0.99158556, 0.11857686, 0.2209226 ],
       [0.17126344, 0.20782432, 0.65233133, 0.65147777],
       [0.89697492, 0.71695382, 0.13064946, 0.68791349]])

In [20]:
np.random.randn(5,5)

array([[-1.2431222 ,  0.89088415, -1.35317491, -1.78717203,  0.56486619],
       [ 1.13700219,  0.34239754,  0.92621693, -0.01993219,  0.28050722],
       [-0.06101349,  1.25440423, -0.30537371,  0.32120344, -0.66646093],
       [ 0.69532707,  0.95561559, -1.21411642,  0.14947877, -0.33750031],
       [-0.53238397,  1.48105166,  1.35569056,  1.24582837,  0.76307101]])

In [25]:
np.random.randint(1,100,(2,2))

array([[84, 74],
       [52, 27]])

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [29]:
arr = np.arange(25)

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [34]:
arr.shape

(25,)

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr = arr.reshape(5,5)

In [38]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranarr.max()

43

In [40]:
ranarr.argmax()

7

In [41]:
ranarr.min()

1

In [42]:
ranarr.argmin()

5

In [43]:
ranarr.dtype

dtype('int64')

In [44]:
myarr = np.random.rand(4)

In [45]:
myarr

array([7.78765841e-04, 9.92211559e-01, 6.17481510e-01, 6.11653160e-01])

In [46]:
myarr.dtype

dtype('float64')