In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
slice_of_array = arr[0:5]

In [13]:
slice_of_array

array([0, 1, 2, 3, 4])

In [14]:
slice_of_array[:] = 99

In [15]:
slice_of_array

array([99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy()

In [18]:
arr_copy[:] = 100

In [19]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d.shape

(3, 3)

In [24]:
arr_2d[0]

array([ 5, 10, 15])

In [25]:
arr_2d[2]

array([35, 40, 45])

In [26]:
arr_2d[1][1]

25

In [27]:
arr_2d[1,1]

25

In [28]:
arr_2d[0,2]

15

In [29]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [30]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
arr = np.arange(1,11)

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [34]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])